version: '3.4'

services:
  openlablog.api:
    image: ${DOCKER_REGISTRY-}openlablogapi
    build:
      context: .
      dockerfile: OpenLabLog.Api/Dockerfile
    environment:
        - DB_PW
    depends_on:
        - db
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    volumes:
      - mssql-server-openlablog-data:/var/opt/mssql/data
    environment:
        SA_PASSWORD: "${DB_PW}"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Enterprise"
    ports:
      - "1733:1433"
volumes:
  mssql-server-openlablog-data: {}